# Generated by Django 5.0.6 on 2024-06-17 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0010_order_payment_intent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_intent_id',
        ),
    ]
